### ISSUE TITLE
wintile@nowsci.com does not exist after unzipping wintile@nowsci.com.zip

### ISSUE THREAD

**Issue by Medik55** [Fmstrat/wintile#144]
Hello, I am trying to install this and I am getting an error after the ```unzip wintile@nowsci.com.zip``` step in the installation. The error is as follows
```cp: cannot stat 'wintile@nowsci.com': No such file or directory```
which leads me to believe that the file that is created and copied into the gnome extensions directory is not being created or generated properly. 

I have tried installing from both the master branch and develop branch and both times I got this error. I am using GNOME Shell 42.5 on Ubuntu 22.04. If there are any other details that would be helpful in solving this, please let me know. 

Here is a screenshot I grabbed after building and unzipping ```wintile@nowsci.com.zip```
![image](https://github.com/Fmstrat/wintile/assets/65376397/1d468de9-df6d-4c30-9f28-6b211809aa87)

**Comment by GrylledCheez** [comment]
It unzipped all the files in the directory you're in, instead of in it's own directory.

We'll update the installation instructions.

In the meantime
```bash
unzip -d wintile@nowsci.com wintile@nowsci.com.zip
```

**Comment by GrylledCheez** [comment]
Fixed in [f4922274d29c1493635828c7d7b3b193672490be](https://github.com/Fmstrat/wintile/commit/f4922274d29c1493635828c7d7b3b193672490be)

**Comment by Medik55** [comment]
Hi, thank you so much for the help! I have a couple more questions if you don't mind. I'm still having a little bit of trouble getting wintile to install and run properly. What should the correct file structure look like within ``` ~/.local/share/gnome-shell/extensions/``` ? And the program GNOME Tweaks is mentioned in the ReadMe for customization. Is it a required dependency for wintile to run?

**Comment by GrylledCheez** [comment]
First, make sure that you aren't running those commands as root/sudo

Please paste the output of `ls -l ~/.local/share/gnome-shell/extensions`

Also, paste the output by following the updated instructions in the current develop README.md

**Comment by Medik55** [comment]
Here is everything up to the copy:
![image](https://github.com/Fmstrat/wintile/assets/65376397/34380c74-5fd6-412a-b96c-1fa31b5084e0)

and here is what is in ```gnome-shell/extensions``` and ```gnome-shell/extensions/wintile@nowsci.com``` after tthe copy:
![image](https://github.com/Fmstrat/wintile/assets/65376397/2be8a783-ca75-4702-b075-7cd587a3a2a7)

**Comment by Medik55** [comment]
I have restarted my computer and I am still not able to use the extension by keyboard shortcuts or dragging. Do you have any suggestions as to something I could be missing? So sorry for the trouble.

**Comment by GrylledCheez** [comment]
Go here in a chrome browser and make sure the extension is enabled. 
If not, enable it. 
If it is, turn on debugging and run this in a terminal as a normal user
```journalctl -qf |grep -i -e Wintile -e 'js error' ```

https://extensions.gnome.org/local/

Also, are you using Wayland or Xorg?

**Comment by GrylledCheez** [comment]
I can't do much without some debug output.

Installing gnome-tweaks is recommended at this point.

**Comment by GrylledCheez** [comment]
Still run that command and post it here.

**Comment by GrylledCheez** [comment]
Ok, I found your issue. gnome-browser-connector is only for 23.04 and after. 

Older ones need to use chrome-gnome-shell
https://launchpad.net/ubuntu/+source/chrome-gnome-shell
```sudo apt-get install chrome-gnome-shell```

**Comment by GrylledCheez** [comment]
Just curious if that fixed your issue. Hopefully it does.

**Comment by GrylledCheez** [comment]
@Medik55, just checking 1 last time.
